#! /usr/bin/bash

if [[ $# -eq 0 ]]; then
    echo "Pass the name of the selected config"
    exit 1
fi

src_file=./config/$1.toml
dest_dir=~/.config/blaze
dest_file=$dest_dir/config.toml

if [[ ! -f $src_file ]]; then
    echo "No such file as $src_file"
    exit 1
fi

mkdir -p $dest_dir
cp $src_file $dest_file
echo "Config copied to $dest_file"
