#! /usr/bin/env bash

src_dir=./config
src_file=$src_dir/$1.toml
dest_dir=~/.config/blaze
dest_file=$dest_dir/config.toml

if [[ $# -eq 0 ]]; then
    echo "Select a config from the list:"
    for entry in $src_dir/*; do
        echo $(basename $entry .toml)
    done
    exit 1
fi

if [[ ! -f $src_file ]]; then
    echo "No such file as $src_file"
    echo "Run the command without arguments to see the available configs"
    exit 1
fi

mkdir -p $dest_dir
cp $src_file $dest_file
echo "Config copied to $dest_file"
