[global]
new_line = false
padding = ""

[prompt]
string = " ❯ "
foreground = ""
error_foreground = ""

[connector]
character = " "
foreground = ""
background = ""
dim = false

[directory]
basename_only = false

[execution_time]
precision = 1
display_from = 2.0
display_fractional_until = 10.0

[git_branch]
ignore = []

[git_status]
count = true
spacing = " "
clean = "✓"
ahead = "↑"
behind = "↓"
stashed = "$"
untracked = "?"
conflicted = "="
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[date]
format = "%F"

[time]
format = "%T"

[[module]]
name = "directory"
align = "left"
inner_prefix = ""
inner_suffix = ""
outer_prefix = ""
outer_suffix = ""
background = ""
foreground = "blue"
bold = true
dim = false
italic = false
underline = false

[[module]]
name = "git_branch"
align = "left"
inner_prefix = " "
inner_suffix = ""
outer_prefix = " "
outer_suffix = ""
background = ""
foreground = "green"
bold = false
dim = false
italic = false
underline = false

[[module]]
name = "git_status"
align = "left"
inner_prefix = ""
inner_suffix = ""
outer_prefix = " "
outer_suffix = ""
background = ""
foreground = "green"
bold = false
dim = false
italic = false
underline = false

[[module]]
name = "execution_time"
align = "left"
inner_prefix = "⌛︎"
inner_suffix = ""
outer_prefix = " "
outer_suffix = ""
background = ""
foreground = "yellow"
bold = false
dim = false
italic = false
underline = false
