[global]
padding = ""

[prompt]
string = "❯ "
foreground = "#ffffff"
error_foreground = "#e83030"

[connector]
character = "─"
foreground = "#ffffff"

[directory]
limit = 10
from_repository = true

[duration]
display_from = 2.0

[date]
format = "%F"

[time]
format = "%T"

[status]
non_zero_only = true

[git_status]
clean = ""

# [[module]]
# name = "user"
# inner_suffix = " "
# foreground = "#513559"

[[module]]
name = "directory"
inner_prefix = "  "
inner_suffix = " "
foreground = "#007aff"

[[module]]
name = "git_branch"
inner_prefix = " "
inner_suffix = " "
foreground = "#25c145"

[[module]]
name = "git_status"
inner_suffix = " "
foreground = "#25c145"

[[module]]
name = "duration"
inner_prefix = "⌛︎"
inner_suffix = " "
foreground = "#e38029"

[[module]]
name = "status"
inner_prefix = "⚠ "
inner_suffix = " "
foreground = "#e83030"

[[module]]
name = "date"
align = "right"
padding = " "
foreground = "#ffffff"

[[module]]
name = "time"
align = "right_prompt"
inner_suffix = " "
foreground = "#ffffff"

[[module]]
name = "fixed"
position = 0
outer_prefix = "╭─"
outer_suffix = " "
foreground = "#ffffff"

[[module]]
name = "fixed"
level = 2
outer_prefix = "╰─ "
foreground = "#ffffff"

[[module]]
name = "fixed"
align = "right"
outer_suffix = "─╮"
foreground = "#ffffff"

[[module]]
name = "fixed"
align = "right_prompt"
outer_suffix = "─╯"
foreground = "#ffffff"
