[global]
padding = ""

[prompt]
string = "❯ "
foreground = "#ffffff"
error_foreground = "#e83030"

[directory]
limit = 10
from_repository = true

# [[module]]
# name = "user"
# inner_suffix = " "
# foreground = "#513559"

[[module]]
name = "directory"
inner_prefix = "  "
inner_suffix = " "
foreground = "#007aff"

[[module]]
name = "git_branch"
inner_prefix = " "
inner_suffix = " "
foreground = "#25c145"

[[module]]
name = "git_status"
inner_suffix = " "
foreground = "#25c145"

[[module]]
name = "duration"
inner_prefix = "⌛︎"
inner_suffix = " "
foreground = "#e38029"

[[module]]
name = "status"
inner_prefix = "⚠ "
inner_suffix = " "
foreground = "#e83030"

# [[module]]
# name = "time"
# inner_prefix = " "
# inner_suffix = " "
# foreground = "#868686"
