# This config is intended to be used for development only.
# Makes it easier to spot visual artifacts.

[global]
new_line = true

[prompt]
string = "\n❯ "
foreground = "green"
error_foreground = "red"

[connector]
character = "─"

[[module]]
execute = "echo 'development only config'"
outer_suffix = ""
background = "#513559"
foreground = "#ffffff"

[[module]]
name = "directory"
inner_prefix = "  "
outer_suffix = ""
background = "#007aff"
foreground = "#ffffff"

[[module]]
name = "separator"
outer_suffix = ""
background = "default"

[[module]]
name = "git_branch"
inner_prefix = "  "
outer_suffix = ""
background = "#25c145"
foreground = "#ffffff"
padding = ""

[[module]]
name = "git_status"
outer_suffix = ""
background = "#25c145"
foreground = "#ffffff"
padding = ""

[[module]]
name = "fixed"
outer_suffix = ""
background = "15"

[[module]]
name = "fixed"
outer_suffix = ""
background = "30"

[[module]]
name = "fixed"
outer_suffix = ""
background = "180"

[[module]]
execute = "echo ---///---"
align = "right"
outer_prefix = ""
background = "4"
foreground = "#ffffff"

[[module]]
name = "user"
align = "right"
outer_prefix = ""
background = "#25c145"
foreground = "#ffffff"

[[module]]
name = "separator"
align = "right"
outer_prefix = ""
background = "default"

[[module]]
name = "host"
align = "right"
outer_prefix = ""
background = "#e38029"
foreground = "#ffffff"

[[module]]
name = "status"
align = "right"
inner_prefix = "⚠ "
outer_prefix = ""
background = "#e83030"
foreground = "#ffffff"

[[module]]
name = "date"
align = "right_prompt"
inner_suffix = " "
outer_prefix = ""
background = "81"
foreground = "#ffffff"

[[module]]
name = "date"
align = "right_prompt"
background = "81"
foreground = "#ffffff"

[[module]]
name = "time"
align = "right_prompt"
inner_prefix = " "
background = "#868686"
foreground = "#ffffff"
