[global]
padding = ""

[prompt]
string = "\n❯ "
foreground = "#25c145"
error_foreground = "#e83030"
new_line = true

[git_status]
clean = ""

# [[module]]
# name = "user"
# inner_prefix = " "
# outer_suffix = ""
# background = "#513559"
# foreground = "#ffffff"

[[module]]
name = "directory"
inner_prefix = "   "
outer_suffix = ""
background = "#007aff"
foreground = "#ffffff"

[[module]]
name = "git_branch"
inner_prefix = "  "
outer_suffix = ""
background = "#25c145"
foreground = "#ffffff"

[[module]]
name = "git_commit"
inner_prefix = "  "
outer_suffix = ""
background = "#25c145"
foreground = "#ffffff"

[[module]]
name = "git_status"
outer_suffix = ""
background = "#25c145"
foreground = "#ffffff"

[[module]]
name = "duration"
inner_prefix = " ⌛︎"
outer_suffix = ""
background = "#e38029"
foreground = "#ffffff"

[[module]]
name = "status"
inner_prefix = " ⚠ "
outer_suffix = ""
background = "#e83030"
foreground = "#ffffff"

# [[module]]
# name = "time"
# inner_prefix = "  "
# outer_suffix = ""
# background = "#868686"
# foreground = "#ffffff"
